const express = require('express');
const app = express();
app.use(express.json());
let valid=['037-2025-26','038-2025-26','039-2025-26','2023/001'];
let voted=new Set();
let tokens=new Map();
let votes={A:0,B:0,C:0};
function genToken(){return 'LIB-'+Math.random().toString(36).substring(2,7).toUpperCase();}
function nav(){return '<div style="background:#0a3d62;color:white;padding:12px;text-align:center"><a href="/table1" style="color:white;margin:10px">TABLE1</a><a href="/table2" style="color:white;margin:10px">TABLE2</a><a href="/dashboard" style="color:white;margin:10px">DASHBOARD</a></div>';}
app.get('/',(req,res)=>res.redirect('/table1'));
app.get('/table1',(req,res)=>{res.send(nav()+'<div style="max-width:500px;margin:20px auto;background:white;padding:20px"><h2>TABLE 1 - Verification</h2><input id="sid" placeholder="Enter ID" style="width:100%;padding:10px"><button onclick="gen()" style="width:100%;padding:10px;background:#0a3d62;color:white">Generate Token</button><div id="r" style="margin-top:10px"></div></div><script>async function gen(){let id=document.getElementById("sid").value.trim();let r=await fetch("/api/generate-token",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentID:id})});let d=await r.json();document.getElementById("r").innerHTML=d.token?"<b>TOKEN: "+d.token+"</b>":""+d.message}</script>');});
app.get('/table2',(req,res)=>{res.send(nav()+'<div style="max-width:500px;margin:20px auto;background:white;padding:20px"><h2>TABLE 2 - Voting</h2><input id="tok" placeholder="Paste LIB- token" style="width:100%;padding:10px"><button onclick="check()" style="width:100%;padding:10px">Validate</button><div id="msg"></div><div id="area" style="display:none"><div onclick="sel='A'" style="border:1px solid #ddd;padding:10px;margin:5px"><img src="https://i.pravatar.cc/100?img=12" style="width:50px;border-radius:50%"> William Kollie</div><div onclick="sel='B'" style="border:1px solid #ddd;padding:10px;margin:5px"><img src="https://i.pravatar.cc/100?img=8" style="width:50px;border-radius:50%"> James Peters</div><div onclick="sel='C'" style="border:1px solid #ddd;padding:10px;margin:5px"><img src="https://i.pravatar.cc/100?img=5" style="width:50px;border-radius:50%"> Princess Doe</div><button onclick="vote()" style="width:100%;padding:10px;background:green;color:white">CONFIRM VOTE</button></div></div><script>let sel=null;async function check(){let t=document.getElementById("tok").value;let r=await fetch("/api/validate-token",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:t})});let d=await r.json();document.getElementById("msg").innerText=d.message;if(d.success)document.getElementById("area").style.display="block"}async function vote(){let t=document.getElementById("tok").value;let r=await fetch("/api/vote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:t,candidateID:sel})});let d=await r.json();document.getElementById("msg").innerText=d.message}</script>');});
app.get('/dashboard',(req,res)=>{res.send(nav()+'<div style="max-width:600px;margin:20px auto;background:white;padding:20px;text-align:center"><h1>LIVE DASHBOARD</h1><h2>Total: <span id="tot">0</span></h2><div id="res"></div><div id="win"></div></div><script>async function load(){let r=await fetch("/api/results");let d=await r.json();document.getElementById("tot").innerText=d.total;let names=["William","James","Princess"];let vals=[d.counts.A,d.counts.B,d.counts.C];let html="";let max=0,win="";for(let i=0;i<3;i++){if(vals[i]>max){max=vals[i];win=names[i]}let perc=d.total?Math.round(vals[i]/d.total*100):0;html+="<div style="padding:10px;background:#f0f0f0;margin:5px">"+names[i]+": "+vals[i]+" ("+perc+"%)</div>"}document.getElementById("res").innerHTML=html;if(d.total>0)document.getElementById("win").innerHTML="<h2>LEADING: "+win+"</h2>"}setInterval(load,2000);load();</script>');});
app.post('/api/generate-token',(req,res)=>{let s=req.body.studentID;if(!valid.includes(s))return res.json({message:'ID not found'});if(voted.has(s))return res.json({message:'Already voted'});let t=genToken();tokens.set(t,{used:false});voted.add(s);res.json({token:t,success:true});});
app.post('/api/validate-token',(req,res)=>{let t=tokens.get(req.body.token);if(!t)return res.json({message:'Invalid token',success:false});if(t.used)return res.json({message:'Token burned',success:false});res.json({message:'Valid token',success:true});});
app.post('/api/vote',(req,res)=>{let t=tokens.get(req.body.token);if(!t||t.used)return res.json({message:'Invalid token'});votes[req.body.candidateID]++;t.used=true;res.json({message:'Vote counted!'});});
app.get('/api/results',(req,res)=>{let total=votes.A+votes.B+votes.C;res.json({counts:votes,total});});
module.exports=app;
